# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-18.04

steps:
- script: yarn test:e2e:docker:build
  displayName: 'yarn test:e2e:docker:build'

- script: yarn test:e2e:docker:run
  displayName: 'yarn test:e2e:docker:run'
